<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="WebApplication.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <h3 aria-atomic="False">Founded in June 2015, NewEra is a language enrichment centre dedicated to teach children aged between 4-12 years old Chinese, English and Malay. After a few years of practicing, we have come out with an effective teaching method which we named it as &quot; NewEra Learning System " with just a simple three steps and corresponding teaching materials so their can master three languages easily. We hope this teaching method can benefit up to 200,000 children across the country in the future.

    </h3>

    <asp:Panel ID="Panel1" runat="server">
        <table style="margin-right: 117px;" class="nav-justified">
            <tr>
                <td style="width: 412px; height: 136px;">
                    <asp:Image ID="Image1" runat="server" ImageUrl="~/Picture/flag-1.png" Height="93px" ImageAlign="Middle" Width="93px" />
                    <h2 style="width: 362px; height: 94px"><span style="color: rgb(0, 0, 0); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">To be the best children education brand. Starting footsteps from Malaysia towards the whole world.</span></td>
                  <td style="width: 439px; height: 136px;">
                    <asp:Image ID="Image2" runat="server" ImageUrl="~/Picture/target-1.png"  Height="93px" ImageAlign="Left" Width="93px" />
                    <h2 style="width: 362px; height: 94px"><span style="color: rgb(0, 0, 0); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Insist on building the best education for children, starting off with a sincere heart.</span></h2>
                </td>
                 <td style="width: 466px; height: 136px;">
                    <asp:Image ID="Image3" runat="server" ImageUrl="~/Picture/badge.png" Height="93px" ImageAlign="Left" Width="93px"/>
                    <h2 style="width: 362px; height: 94px"><span style="color: rgb(0, 0, 0); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Child-centered, so they can learn three languages efficiently and happily</span></h2>
                </td>
            </tr>
            </table>       
        <table style="margin-right: 117px;" class="nav-justified">
            <tr>
                   <td style="width: 466px; height: 136px;">2015:<h5 class="timeline-item__card-title" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-family: 方正兰亭中黑_GBK, sans-serif; color: rgb(33, 37, 41); font-size: 15px; font-weight: 600; line-height: 1.5em; letter-spacing: 0.3px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: 487px;" aria-multiselectable="False">NewEra officially established </h5></td>
                 <td style="width: 466px; height: 136px;">2016:<h5 class="timeline-item__card-title" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-family: 方正兰亭中黑_GBK, sans-serif; color: rgb(33, 37, 41); font-size: 15px; font-weight: 600; line-height: 1.5em; letter-spacing: 0.3px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: 517px; height: 45px;" aria-multiselectable="False">Compilation and publication of own teaching materials, such as textbooks, flashcards, reading books, message books and etc</h5>
                </td>
                 <td style="width: 466px; height: 136px;">2017:<h5 class="timeline-item__card-title" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-family: 方正兰亭中黑_GBK, sans-serif; color: rgb(33, 37, 41); font-size: 15px; font-weight: 600; line-height: 1.5em; letter-spacing: 0.3px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: 520px;">Official launch of the second batch books (improved version) which have better teaching elements</h5>
                </td>
            </tr>
            <tr>
             <td style="width: 466px; height: 136px;">2018:<h5 class="timeline-item__card-title" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-family: 方正兰亭中黑_GBK, sans-serif; color: rgb(33, 37, 41); font-size: 15px; font-weight: 600; line-height: 1.5em; letter-spacing: 0.3px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: 489px;">Extensive training and resources investment for more qualified teachers</h5>
                </td>
              <td style="width: 466px; height: 136px;">2019:<h5 class="timeline-item__card-title" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-family: 方正兰亭中黑_GBK, sans-serif; color: rgb(33, 37, 41); font-size: 15px; font-weight: 600; line-height: 1.5em; letter-spacing: 0.3px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: 512px;">Official launch of NewEra Go Online and develop Online Platform for course purchase</h5>
                    <br class="Apple-interchange-newline" />
                </td>
 <td style="width: 466px; height: 136px;">2020:<h5 class="timeline-item__card-title" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-family: 方正兰亭中黑_GBK, sans-serif; color: rgb(33, 37, 41); font-size: 15px; font-weight: 600; line-height: 1.5em; letter-spacing: 0.3px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: 549px;">Official launch of NewEra Go Online and develop Online Platform for course purchase</h5>
                </td>
            </tr>
        </table>
        <tr>



            <br />
            <table class="nav-justified">
                <tr>
                    <td>
                        <h2 class="elementor-heading-title elementor-size-default" style="box-sizing: border-box; margin: 0px; font-family: 方正兰亭中黑_GBK, sans-serif; color: rgb(0, 0, 0); font-size: 45px; font-weight: var( --e-global-typography-primary-font-weight ); line-height: 1; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The founder&#39;s story</h2>
                        <p class="elementor-heading-title elementor-size-default" style="box-sizing: border-box; margin: 0px; font-family: 方正兰亭中黑_GBK, sans-serif; color: rgb(0, 0, 0); font-size: 45px; font-weight: var( --e-global-typography-primary-font-weight ); line-height: 1; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            <asp:Image ID="Image4" runat="server" ImageUrl="~/Picture/Little-Master-since-2015-1024x768.jpg" />
                        </p>
                        <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(66, 66, 66); font-family: Roboto, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            Over the past year maybe many people will be curious that<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: bolder;">#why am I so insisted to startup NewEra Online?</strong><span>&nbsp;</span>As the person that you knew more than ten years ago, I am actually just a kindergarten teacher after all. I remembered when I was a part-time tutor, I have met some senior students who can&#39;t even do the first grade exercise. It’s not that they are not hardworking, it’s that they were unable to lay a solid learning foundation when they were young. And our traditional teaching method can not help them at all, this make me felt very powerless!<span>&nbsp;</span><img alt="😭" class="emoji" draggable="false" role="img" src="https://s.w.org/images/core/emoji/13.1.0/svg/1f62d.svg" style="box-sizing: border-box; vertical-align: -0.1em !important; border: none; display: inline !important; box-shadow: none; height: auto; width: 1em !important; margin: 0px 0.07em !important; background: none !important; padding: 0px !important; max-width: 100%; border-radius: 0px;" /></p>
                        <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(66, 66, 66); font-family: Roboto, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            &nbsp;</p>
                        <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(66, 66, 66); font-family: Roboto, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            I told my husband that time, I have a set of methods which can teach every children in a good manner. But it would takes a lot of time, money and manpower to complete it. And I don’t even know whether I can succeed? I’m so grateful that I met someone who understands me, he told me to do what I want, as long as I think it’s right. So accidentally, the<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: bolder;"># &quot;NewEra&quot; was born!</strong></p>
                        <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(66, 66, 66); font-family: Roboto, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            &nbsp;</p>
                        <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(66, 66, 66); font-family: Roboto, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            At the beginning, we don’t even have a single card or a book. Every day we would immersed in composing books and planning teaching method, we spent all the money we earned in teaching system research and development. Many people said that we have wishful thinking, what great things can be done by a kindergarten teacher and a white-collar? Can your things work? Can your stuff compete with other big brands? This is what we have heard most in the past few years. But I believe that no one is perfect,<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: bolder;">#we also firmly believe that there is no best stuff but better stuff</strong>. As long as you don’t give up, you can achieve what you want. You can say that we are crazy but<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: bolder;">#dreams are realized by lunatics</strong>.<span>&nbsp;</span><img alt="🤪" class="emoji" draggable="false" role="img" src="https://s.w.org/images/core/emoji/13.1.0/svg/1f92a.svg" style="box-sizing: border-box; vertical-align: -0.1em !important; border: none; display: inline !important; box-shadow: none; height: auto; width: 1em !important; margin: 0px 0.07em !important; background: none !important; padding: 0px !important; max-width: 100%; border-radius: 0px;" /></p>
                        <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(66, 66, 66); font-family: Roboto, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            &nbsp;</p>
                        <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(66, 66, 66); font-family: Roboto, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            We spent<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: bolder;">#2190 days to establish the NewEra</strong>, from zero book to more than 100 self-published books and own a unique set of teaching method to teach every children well. From only five students in the beginning<br style="box-sizing: border-box;" /> to expansion of four branches. If you ask me are our journey hard? I would say it is pretty hard! You can complain or you can enjoy the process and have fun. But for many careers, not every hard work will be paid off, you may lose your capital at the end. But in education field, I think I achieved more because I can help many people. This is not the satisfaction that you can get by making money.<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: bolder;">#Children’s growth and learning progress</strong>,<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: bolder;">#Parents’ recognition &amp; positive review</strong><span>&nbsp;</span>are<span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: bolder;">#our 
                            greatest accomplishment</strong>.<span>&nbsp;</span><img alt="🤩" class="emoji" draggable="false" role="img" src="https://s.w.org/images/core/emoji/13.1.0/svg/1f929.svg" style="box-sizing: border-box; vertical-align: -0.1em !important; border: none; display: inline !important; box-shadow: none; height: auto; width: 1em !important; margin: 0px 0.07em !important; background: none !important; padding: 0px !important; max-width: 100%; border-radius: 0px;" /></p>
                        <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(66, 66, 66); font-family: Roboto, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            I hope that no matter what level of study the children is, we are able to teach them well according to their condition.</p>
                        <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(66, 66, 66); font-family: Roboto, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            <strong style="box-sizing: border-box; font-weight: bolder;">#NewEra #Never give up on any children #Give the best education to children #This is always my uphold philosophy</strong></p>
                        <p class="elementor-heading-title elementor-size-default" style="box-sizing: border-box; margin: 0px; font-family: 方正兰亭中黑_GBK, sans-serif; color: rgb(0, 0, 0); font-size: 45px; font-weight: var( --e-global-typography-primary-font-weight ); line-height: 1; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            &nbsp;</p>
                    </td>
                </tr>
            </table>
    </asp:Panel>
</asp:Content>
